# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('gdbr_rcpparma_hello_world', PACKAGE = 'gdbr')
}

rcpparma_outerproduct <- function(x) {
    .Call('gdbr_rcpparma_outerproduct', PACKAGE = 'gdbr', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('gdbr_rcpparma_innerproduct', PACKAGE = 'gdbr', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('gdbr_rcpparma_bothproducts', PACKAGE = 'gdbr', x)
}

gdbrcpp <- function(D, y) {
    .Call('gdbr_rcpp_gdbr', PACKAGE = 'gdbr', D, y)
}
